# Generated by Django 5.0.3 on 2024-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "느림"), (2, "중간"), (3, "빠름")]
                    ),
                ),
            ],
        ),
    ]
